# Generated by Django 3.0.8 on 2020-07-08 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.IntegerField(choices=[(1, 'Burgers'), (2, 'Chinese'), (3, 'Italian'), (4, 'Japanese'), (5, 'Mexican'), (6, 'Thai'), (7, 'Indian'), (8, 'Greek'), (9, 'Swiss'), (10, 'Pizza'), (11, 'Vegetarian'), (12, 'Other')], default=12)),
                ('country', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=5)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('email', models.CharField(blank=True, max_length=200, unique=True)),
                ('opening_hours', models.CharField(max_length=200)),
                ('price_level', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('restaurant_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('take_reservations', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('take_away', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
