# Generated by Django 3.0.8 on 2020-07-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.IntegerField(choices=[(1, 'Burgers'), (2, 'Chinese'), (3, 'Italian'), (4, 'Japanese'), (5, 'Mexican'), (6, 'Thai'), (7, 'Indian'), (8, 'Greek'), (9, 'Swiss'), (10, 'Pizza'), (11, 'Vegetarian'), (12, 'Other')], default=12),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
