--- 
dependencies: 
  - python=3.7
  - psycopg2
  - pip:
      - flake8
      - djangorestframework==3.11.0
      - djangorestframework-simplejwt==4.4.0
      - coreapi==2.3.3
      - markdown==3.2.2
      - django-filter==2.3.0
      - gunicorn==20.0.4
      - Pillow==7.1.2
      - django-cors-headers==3.4.0
name: lunaProject