export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const VERIFICATION_ERROR = 'VERIFICATION_ERROR';

export const GENERAL_ERROR = 'NETWORK_ERROR';
export const GENERAL_ERROR_CLEAR = 'GENERAL_ERROR_CLEAR';

export const GET_TOP_4_RESTAURANTS = 'TOP_4_RESTAURANTS';
export const CREATE_RESTAURANT = 'CREATE_RESTAURANT';
export const GET_ALL_RESTAURANTS = 'GET_ALL_RESTAURANTS';