# Generated by Django 3.0.8 on 2020-07-05 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_auto_20200705_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='users_who_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
